### PR TITLE
V4110

### PR DESCRIPTION
**Pull request by nonelse**
- Update libraries
 - Send `os_build`
 - Remove `hasAttributionListener` check
 - Read config file
 - Send fire ad id information

### CODE REVIEW

**Comment by uerceg** [comment]
@adjust/integration

**Comment by falconxunit** [comment]
Can i get this request

**Comment by uerceg** [comment]
@falconxunit This will be live in next couple of days.

**Comment by luckey01** [comment]
I'll get @easteracrobat (chris) onto it

**Pull request merged**
